fint:
  relation:
    base-url: https://api.felleskomponent.no
  consumer:
    pod-url: http://localhost:8080
    base-url: ${fint.relation.base-url}
    domain: utdanning
    packageName: ${fint.consumer.package}
    org-id: fintlabs.no

spring:
  threads:
    virtual:
      enabled: true
  kafka:
    consumer:
      group-id: fint-core-consumer
    bootstrap-servers: kafka:9092
logging:
  level:
    org.apache.kafka: OFF
    no.fintlabs.cache: DEBUG
