apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
  - org-values.yaml
  - adapter-gateway-ingress.yaml
components:
  - ../../../components/org
patches:
  - target:
      kind: IngressRoute
      name: fint-core-client-api-ingress
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: 'Host(`beta.felleskomponent.no`) && PathPrefix(`/`) && !PathPrefix(`/provider`) && !PathPrefix(`/{domain:[a-z]+}/{package:[a-z]+}/provider`) && (!PathPrefix(`/okonomi`) || (HeadersRegexp(`x-fint-version-override`, `(?i)^v4$`) || (!HeadersRegexp(`x-fint-version-override`, `(?i)^v3$`) && HeadersRegexp(`x-fint-model-version`, `(?i)^v4$`)))) && HeadersRegexp(`x-org-id`, `.+`) && !HeadersRegexp(`x-org-id`, `(^|\.)(afk\.no|agderfk\.no|bfk\.no|ffk\.no|innlandetfylke\.no|mrfylke\.no|nfk\.no|ofk\.no|oslo\.kommune\.no|rogfk\.no|telemarkfylke\.no|tromsfylke\.no|trondelagfylke\.no|vestfoldfylke\.no|vlfk\.no)$`)'
      - op: add
        path: /spec/routes/0/priority
        value: 1000
  - target:
      kind: Application
      name: fint-core-adapter-gateway
    patch: |-
      - op: replace
        path: /spec/ingress
        value:
          enabled: false
