apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
  - org-values.yaml
components:
  - ../../../components/org
patches:
  - target:
      kind: IngressRoute
      name: fint-core-client-api-ingress
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: 'Host(`beta.felleskomponent.no`) && PathPrefix(`/`) && !PathPrefix(`/provider`) && !PathPrefix(`/{domain:[a-z]+}/{package:[a-z]+}/provider`) && HeadersRegexp(`x-org-id`, `^novari\.no$`)'
      - op: add
        path: /spec/routes/0/priority
        value: 1000
