fint:
  relation:
    base-url: https://api.felleskomponent.no
  consumer:
    base-url: ${fint.relation.base-url}
    org-id: ${fint.org-id} # fint.org-id is sat by the FlaisApplication in environment
    event:
      answer-deadline: 15m
      retention: 30m

spring:
  application:
    name: fint-core-client-api
  config:
    import:
      - classpath:shared-mongodb.yaml
  mongodb:
    database: fint
  threads:
    virtual:
      enabled: true
  kafka:
    security:
      protocol: SSL
    consumer:
      group-id: fint-core-client-api-${fint.org-id}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health

logging:
  level:
    org.apache.kafka: WARN
