# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2

  updates:
    - package-ecosystem: "gradle"
      directories:
        - "/"
        - "/buildSrc"
        - "/fint-core-consumer"
        - "/fint-core-provider-gateway"
        - "/fint-core-shared"
      schedule:
        interval: "weekly"
        day: "monday"
        time: "06:00"
        timezone: "Europe/Oslo"
      open-pull-requests-limit: 5
      labels:
        - "dependencies"
        - "gradle"
      commit-message:
        prefix: "deps"
        include: "scope"
      groups:
        spring:
          patterns:
            - "org.springframework*"
            - "org.springdoc*"
            - "io.spring.gradle:*"
        kotlin:
          patterns:
            - "org.jetbrains.kotlin*"
            - "org.jetbrains.kotlinx*"
        fint-novari:
          patterns:
            - "no.fint:*"
            - "no.fintlabs:*"
            - "no.novari:*"
        gradle-plugins:
          patterns:
            - "com.github.ben-manes.versions"
            - "se.patrikerdes.use-latest-versions"
            - "org.jlleitschuh.gradle:*"
        jackson:
          patterns:
            - "com.fasterxml.jackson*"
        gradle-other-minor-patch:
          patterns:
            - "*"
          update-types:
            - "minor"
            - "patch"

    - package-ecosystem: "docker"
      directories:
        - "/fint-core-consumer"
        - "/fint-core-provider-gateway"
      schedule:
        interval: "weekly"
        day: "tuesday"
        time: "06:00"
        timezone: "Europe/Oslo"
      open-pull-requests-limit: 5
      labels:
        - "dependencies"
        - "docker"
      commit-message:
        prefix: "deps"
        include: "scope"
      groups:
        docker-images:
          patterns:
            - "*"

    - package-ecosystem: "docker-compose"
      directory: "/"
      schedule:
        interval: "weekly"
        day: "tuesday"
        time: "06:15"
        timezone: "Europe/Oslo"
      open-pull-requests-limit: 5
      labels:
        - "dependencies"
        - "docker-compose"
      commit-message:
        prefix: "deps"
        include: "scope"
      groups:
        docker-compose-images:
          patterns:
            - "*"

    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
        interval: "weekly"
        day: "wednesday"
        time: "06:00"
        timezone: "Europe/Oslo"
      open-pull-requests-limit: 5
      labels:
        - "dependencies"
        - "github-actions"
      commit-message:
        prefix: "deps"
        include: "scope"
      groups:
        github-actions:
          patterns:
            - "*"
