apiVersion: v1
kind: ConfigMap
metadata:
  name: fint-org
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  id-dotted: ude.oslo.kommune.no
  id-dashed: ude-oslo-kommune-no
  id-underscore: ude_oslo_kommune_no
  org-id-regex: 're:(^|\.)ude\.oslo\.kommune\.no$'
  asset-regex: 're:(^|,)ude\.oslo\.kommune\.no(,|$)'
  host: beta.felleskomponent.no
  base-url: https://beta.felleskomponent.no
  onepassword-itempath: "vaults/aks-beta-vault/items/fint-core-ude-oslo-kommune-no-cluster-beta"
