apiVersion: v1
kind: ConfigMap
metadata:
  name: fint-org
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  id-dotted: fintlabs.no
  id-dashed: fintlabs-no
  id-underscore: fintlabs_no
  host: alpha.felleskomponent.no
  base-url: https://alpha.felleskomponent.no
  onepassword-itempath: "vaults/aks-alpha-vault/items/azurerator"
