package no.novari.core.shared.relation

import no.novari.fint.core.model.FintResourceRef
import org.junit.jupiter.api.Test
import java.nio.file.Path
import kotlin.io.path.exists
import kotlin.io.path.readText
import kotlin.io.path.writeText
import kotlin.test.fail

/**
 * Keeps RELATION_RULES.md at the repository root equal to the rules the code derives from the
 * model. When the two differ, the test rewrites the file and fails, so a change to
 * [RelationRules] or a model version bump cannot merge before the document follows. Commit the
 * rewritten file to make it pass again.
 */
class RelationRulesDocumentTest {
    @Test
    fun `the committed relation rules document matches the rules derived from the model`() {
        val file = repositoryRoot().resolve("RELATION_RULES.md")
        val expected = render(RelationRules.all())
        val committed = if (file.exists()) file.readText() else ""
        if (committed == expected) return

        file.writeText(expected)
        fail(
            buildString {
                appendLine("RELATION_RULES.md did not match the rules derived from the model.")
                appendLine("The file has been rewritten at $file. Review the change and commit it.")
                appendLine()
                (expected.lines() - committed.lines().toSet()).forEach { appendLine("+ $it") }
                (committed.lines() - expected.lines().toSet()).forEach { appendLine("- $it") }
            },
        )
    }

    private fun repositoryRoot(): Path =
        generateSequence(Path.of("").toAbsolutePath()) { it.parent }
            .first { it.resolve("settings.gradle.kts").exists() }

    private fun render(rules: List<RelationRule>): String =
        buildString {
            appendLine(HEADER)
            appendLine()
            rules
                .groupBy { it.sourceRef }
                .entries
                .sortedWith(compareBy({ it.key.domainName }, { it.key.packageName }, { it.key.resourceName }))
                .forEach { (sourceRef, rows) ->
                    appendLine("## `${sourceRef.path()}`")
                    appendLine()
                    appendLine("| Source relation | Target resource | Back-relation | Kind |")
                    appendLine("|---|---|---|---|")
                    rows.forEach { rule ->
                        appendLine(
                            "| `${rule.relationName}` | `${rule.targetRef.path()}` | `${rule.inverseName}` | ${rule.kind.label()} |",
                        )
                    }
                    appendLine()
                }
        }

    private fun FintResourceRef.path() = "$domainName/$packageName/$resourceName"

    private fun RelationRule.Kind.label() =
        when (this) {
            RelationRule.Kind.ONE_TO_MANY -> "One to many"
            RelationRule.Kind.MANY_TO_MANY -> "Many to many"
        }

    private companion object {
        val HEADER =
            """
            # Autorelation rules

            Generated by `RelationRulesDocumentTest` in `fint-core-shared`. Do not edit by hand. The test
            fails when this file does not match the rules the code derives from the model, and rewrites it.
            To regenerate, run the test and commit the result:

            ```
            ./gradlew :fint-core-shared:test --tests '*RelationRulesDocumentTest'
            ```

            Each section is a source resource. Each row says: when a resource of that type is written with a
            link under **Source relation**, the adapter-gateway stores a relation edge, and the client-api
            attaches a back-link under **Back-relation** on the **Target resource** whenever that target is
            served. Nothing is written to the target itself.

            A relation gets a row when all of these hold (see `RelationRules.of`):

            - The model declares an inverse for it.
            - The inverse side is list-valued.
            - If the source relation is list-valued, it is the owning side.
            - The target is in the source's own domain. Common resources such as `person` count as the
              source's domain and appear once per domain and package they are served under.

            **Kind** is *One to many* when the source relation is single-valued, and *Many to many* when both
            sides are list-valued.

            ---
            """.trimIndent()
    }
}
