apiVersion: v1
kind: ConfigMap
metadata:
  name: fint-org
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  id-dotted: mrfylke.no
  id-dashed: mrfylke-no
  id-underscore: mrfylke_no
  org-id-regex: 're:(^|\.)mrfylke\.no$'
  asset-regex: 're:(^|,)mrfylke\.no(,|$)'
  host: beta.felleskomponent.no
  base-url: https://beta.felleskomponent.no
  onepassword-itempath: "vaults/aks-beta-vault/items/fint-core-mrfylke-no-cluster-beta"
