apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: IngressRoute
      name: fint-core-client-api-ingress
    patch: |-
      - op: add
        path: /spec/routes/-
        value:
          kind: Rule
          match: 'Host(`REPLACE`) && PathPrefix(`/administrasjon`) && !PathPrefix(`/{domain:[a-z]+}/{package:[a-z]+}/provider`) && HeadersRegexp(`x-org-id`, `REPLACE`)'
          services:
            - name: fint-core-client-api
              namespace: REPLACE-DASHED
              port: 8080
replacements:
  - source:
      kind: ConfigMap
      name: fint-org
      fieldPath: data.host
    targets:
      - select:
          kind: IngressRoute
          name: fint-core-client-api-ingress
        fieldPaths:
          - spec.routes.1.match
        options:
          delimiter: "`"
          index: 1

  - source:
      kind: ConfigMap
      name: fint-org
      fieldPath: data.org-id-regex
      options:
        delimiter: ":"
        index: 1
    targets:
      - select:
          kind: IngressRoute
          name: fint-core-client-api-ingress
        fieldPaths:
          - spec.routes.1.match
        options:
          delimiter: "`"
          index: 9

  - source:
      kind: ConfigMap
      name: fint-org
      fieldPath: data.id-dashed
    targets:
      - select:
          kind: IngressRoute
          name: fint-core-client-api-ingress
        fieldPaths:
          - spec.routes.1.services.0.namespace
