apiVersion: v1
kind: ConfigMap
metadata:
  name: fint-org
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  id-dotted: bfk.no
  id-dashed: bfk-no
  id-underscore: bfk_no
  org-id-regex: 're:(^|\.)bfk\.no$'
  asset-regex: 're:(^|[,.])bfk\.no(,|$)'
  host: beta.felleskomponent.no
  base-url: https://beta.felleskomponent.no
  onepassword-itempath: "vaults/aks-beta-vault/items/fint-core-bfk-no-cluster-beta"
