apiVersion: v1
kind: ConfigMap
metadata:
  name: fint-org
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  id-dotted: novari.no
  id-dashed: novari-no
  id-underscore: novari_no
  asset-regex: 're:(^|,)novari\.no(,|$)'
  host: alpha.felleskomponent.no
  base-url: https://alpha.felleskomponent.no
  onepassword-itempath: "vaults/aks-alpha-vault/items/fint-core-consumer-cluster-alpha"
