apiVersion: v1
kind: ConfigMap
metadata:
  name: fint-org
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  id-dotted: nfk.no
  id-dashed: nfk-no
  id-underscore: nfk_no
  org-id-regex: 're:(^|\.)nfk\.no$'
  asset-regex: 're:(^|[,.])nfk\.no(,|$)'
  host: beta.felleskomponent.no
  base-url: https://beta.felleskomponent.no
  onepassword-itempath: "vaults/aks-beta-vault/items/fint-core-nfk-no-cluster-beta"
