create table contract (
    user_name varchar(255) not null,
    adapter_id varchar(255),
    org_id varchar(255),
    heartbeat_interval_in_minutes integer not null,
    primary key (user_name)
);

create table capabilities (
    id bigint generated by default as identity,
    user_name varchar(255) not null,
    domain_name varchar(255),
    pkg_name varchar(255),
    resource_name varchar(255),
    full_sync_interval_in_days integer not null,
    delta_sync_interval varchar(255),
    primary key (id)
);

alter table capabilities
    add constraint fkdhx1nil1vrkq5usporrd3hql4 foreign key (user_name) references contract;
