delete from capabilities
where user_name in (select user_name from contract where org_id is null or trim(org_id) = '');

delete from contract
where org_id is null or trim(org_id) = '';

update contract
set org_id = replace(replace(lower(trim(org_id)), '-', '.'), '_', '.');

alter table contract add column id bigint generated by default as identity;

alter table capabilities add column contract_id bigint;

update capabilities
set contract_id = contract.id
from contract
where contract.user_name = capabilities.user_name;

alter table capabilities drop column user_name;

do $$
declare
    primary_key_name text;
begin
    select conname
    into primary_key_name
    from pg_constraint
    where conrelid = 'contract'::regclass and contype = 'p';

    execute format('alter table contract drop constraint %I', primary_key_name);
end $$;

alter table contract add primary key (id);

alter table contract alter column org_id set not null;

alter table contract
    add constraint uk_contract_user_name_org_id unique (user_name, org_id);

alter table capabilities alter column contract_id set not null;

alter table capabilities
    add constraint fk_capabilities_contract foreign key (contract_id) references contract (id);
