create table event_capabilities (
    id bigint generated by default as identity,
    contract_id bigint not null,
    domain_name varchar(255) not null,
    pkg_name varchar(255) not null,
    resource_name varchar(255) not null,
    operation varchar(255) not null,
    primary key (id),
    constraint fk_event_capabilities_contract foreign key (contract_id) references contract (id)
);

create index ix_event_capabilities_contract_id on event_capabilities (contract_id);
