apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
replacements:
  - source:
      kind: ConfigMap
      name: fint-org
      fieldPath: data.id-dotted
    targets:
      - select:
          kind: Application
          name: fint-core-client-api
        fieldPaths:
          - spec.orgId
          - metadata.labels.[fintlabs.no/org-id]
      - select:
          kind: Application
          name: fint-core-adapter-gateway
        fieldPaths:
          - spec.orgId
          - metadata.labels.[fintlabs.no/org-id]
      - select:
          kind: IngressRoute
          name: fint-core-client-api-ingress
        fieldPaths:
          - metadata.labels.[fintlabs.no/org-id]

  - source:
      kind: ConfigMap
      name: fint-org
      fieldPath: data.asset-regex
    targets:
      - select:
          kind: Application
          name: fint-core-adapter-gateway
        fieldPaths:
          - spec.ingress.routes.0.headers.x-allowed-asset-ids

  - source:
      kind: ConfigMap
      name: fint-org
      fieldPath: data.org-id-regex
      options:
        delimiter: ":"
        index: 1
    targets:
      - select:
          kind: IngressRoute
          name: fint-core-client-api-ingress
        fieldPaths:
          - spec.routes.0.match
        options:
          delimiter: "`"
          index: 9

  - source:
      kind: ConfigMap
      name: fint-org
      fieldPath: data.id-dashed
    targets:
      - select:
          kind: Application
          name: fint-core-client-api
        fieldPaths:
          - metadata.namespace
      - select:
          kind: Application
          name: fint-core-adapter-gateway
        fieldPaths:
          - metadata.namespace
      - select:
          kind: IngressRoute
          name: fint-core-client-api-ingress
        fieldPaths:
          - metadata.namespace
          - spec.routes.0.services.0.namespace
      - select:
          kind: Application
          name: fint-core-client-api
        fieldPaths:
          - spec.kafka.acls.0.topic
        options:
          delimiter: "."
          index: 0
      - select:
          kind: Application
          name: fint-core-adapter-gateway
        fieldPaths:
          - spec.kafka.acls.6.topic
        options:
          delimiter: "."
          index: 0

  - source:
      kind: ConfigMap
      name: fint-org
      fieldPath: data.id-underscore
    targets:
      - select:
          kind: Application
          name: fint-core-client-api
        fieldPaths:
          - metadata.labels.[app.kubernetes.io/instance]
        options:
          delimiter: "_"
          index: 1
      - select:
          kind: Application
          name: fint-core-adapter-gateway
        fieldPaths:
          - metadata.labels.[app.kubernetes.io/instance]
        options:
          delimiter: "_"
          index: 1

  - source:
      kind: ConfigMap
      name: fint-org
      fieldPath: data.onepassword-itempath
    targets:
      - select:
          kind: Application
          name: fint-core-client-api
        fieldPaths:
          - spec.onePassword.itemPath
      - select:
          kind: Application
          name: fint-core-adapter-gateway
        fieldPaths:
          - spec.onePassword.itemPath

  - source:
      kind: ConfigMap
      name: fint-org
      fieldPath: data.base-url
    targets:
      - select:
          kind: Application
          name: fint-core-client-api
        fieldPaths:
          - spec.env.[name=fint.relation.base-url].value

  - source:
      kind: ConfigMap
      name: fint-org
      fieldPath: data.host
    targets:
      - select:
          kind: IngressRoute
          name: fint-core-client-api-ingress
        fieldPaths:
          - spec.routes.0.match
        options:
          delimiter: "`"
          index: 1
      - select:
          kind: Application
          name: fint-core-adapter-gateway
        fieldPaths:
          - spec.ingress.routes.0.host
