apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-core-consumer
  namespace: REPLACE-DASHED
  labels:
    app.kubernetes.io/name: fint-core-consumer
    app.kubernetes.io/instance: fint-core-consumer_REPLACE
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: consumer
    app.kubernetes.io/part-of: fint-core
    fintlabs.no/team: core
    fintlabs.no/org-id: REPLACE
spec:
  port: 8080
  orgId: REPLACE
  image: ghcr.io/fintlabs/fint-core-consumer:REPLACE
  replicas: 1
  onePassword:
    itemPath: REPLACE
  env:
    - name: fint.relation.base-url
      value: REPLACE
    - name: JAVA_TOOL_OPTIONS
      value: |
        -XX:MaxRAMPercentage=80
        -XX:+ExitOnOutOfMemoryError
  ingress:
    routes:
      - host: REPLACE
        path: /
        headers:
          x-org-id: REPLACE
  kafka:
    enabled: true
    acls:
      - topic: "fintlabs.fint-core.fint-felleskomponent-event-request"
        permission: admin
  resources:
    requests:
      memory: 2Gi
    limits:
      memory: 2Gi
