apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-core-provider-gateway
  namespace: REPLACE-DASHED
  labels:
    app.kubernetes.io/name: fint-core-provider-gateway
    app.kubernetes.io/instance: fint-core-provider-gateway_REPLACE
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: provider
    app.kubernetes.io/part-of: fint-core
    fintlabs.no/team: core
    fintlabs.no/org-id: REPLACE
spec:
  port: 8080
  orgId: REPLACE
  image: ghcr.io/fintlabs/fint-core-provider-gateway:REPLACE
  onePassword:
    itemPath: REPLACE
  env:
    - name: JAVA_TOOL_OPTIONS
      value: |
        -XX:MaxRAMPercentage=80
        -XX:+ExitOnOutOfMemoryError
  database:
    database: fint-core
  ingress:
    routes:
      - host: REPLACE
        path: /provider
        headers:
          x-org-id: REPLACE
  kafka:
    enabled: true
    acls:
      - topic: "novari-no.fint-core.fint-felleskomponent-event-response"
        permission: admin
      - topic: "novari-no.fint-core.fint-felleskomponent-adapter-heartbeat"
        permission: admin
      - topic: "novari-no.fint-core.fint-felleskomponent-adapter-contract"
        permission: admin
      - topic: "novari-no.fint-core.fint-felleskomponent-adapter-full-sync"
        permission: admin
      - topic: "novari-no.fint-core.fint-felleskomponent-adapter-delta-sync"
        permission: admin
      - topic: "novari-no.fint-core.fint-felleskomponent-adapter-delete-sync"
        permission: admin
  resources:
    limits:
      memory: 3Gi
    requests:
      memory: 3Gi
